[versions]
aboutlibraries = "13.2.1"
agp = "8.12.0"
#androidx-documentfile = "1.1.0"
androidx-documentfile = "1.3"
androidx-lifecycle = "2.10.0-alpha08"
arrow = "2.2.1.1"
coil = "3.3.0"
chip-textfield = "0.7.2-alpha01"
compose-multiplatform = "1.10.1"
compose-settings = "2.26.0"
composeWebviewMultiplatform = "1.0.0-alpha-10"
filekitCompose = "0.12.0"
kermit = "2.0.8"
koin = "4.2.0-RC1"
korlibsIo = "6.0.2"
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"
kotlinxSerialization = "1.10.0"
ksoup = "0.2.5"
ksp = "2.3.5"
ktor = "3.4.0"
multiplatformSettings = "1.3.0"
okio = "3.16.4"
orbit = "11.0.0"
paging = "3.4.1"
pixko = "2.10"
room = "2.7.2"
sqliteBundled = "2.6.2"
telephoto = "0.18.0"
versionCatalogUpdate = "1.0.1"

[libraries]
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
androidx-activity-compose = "androidx.activity:activity-compose:1.12.4"
#androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-documentfile = { module = "com.lazygeniouz:dfc", version.ref = "androidx-documentfile" }
androidx-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqliteBundled" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines" }
arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material-icons-core = "org.jetbrains.compose.material:material-icons-core:1.7.3"
compose-material3 = "org.jetbrains.compose.material3:material3:1.9.0"
compose-navigation3-ui = "org.jetbrains.androidx.navigation3:navigation3-ui:1.1.0-alpha02"
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-settings-extended = { module = "com.github.alorma.compose-settings:ui-tiles-extended", version.ref = "compose-settings" }
compose-settings-ui = { module = "com.github.alorma.compose-settings:ui-tiles", version.ref = "compose-settings" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-webview-multiplatform = { module = "io.github.kdroidfilter:composewebview", version.ref = "composeWebviewMultiplatform" }
filekit-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekitCompose" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekitCompose" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-compose-navigation3 = { module = "io.insert-koin:koin-compose-navigation3", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
korlibs-io = { module = "com.soywiz:korlibs-io", version.ref = "korlibsIo" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerialization" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ktlint = "com.pinterest.ktlint:ktlint-cli:1.8.0"
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
#multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettings" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
orbit-core = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit" }
pixko = { module = "top.kagg886:pixko", version.ref = "pixko" }
telephoto-zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "telephoto" }
chip-textfield = { module = "io.github.dokar3:chiptextfield-m3", version.ref = "chip-textfield" }

[plugins]
aboutlibrariesPlugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
benmanes-versions = "com.github.ben-manes.versions:0.53.0"
buildConfig = "com.github.gmazzo.buildconfig:6.0.7"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
spotless = "com.diffplug.spotless:8.2.1"
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }

[bundles]
coil = [
    "coil-compose",
    "coil-network",
]
room = [
    "androidx-room-paging",
    "androidx-room-runtime",
]
